//
// Created by Akira Mujawar on 11/07/26.
//

#ifndef MEOWENGINE_PHYSICSINTERPOLATIONSYSTEM_HPP
#define MEOWENGINE_PHYSICSINTERPOLATIONSYSTEM_HPP


class PhysicsInterpolationSystem {};


#endif //MEOWENGINE_PHYSICSINTERPOLATIONSYSTEM_HPP