//
// Created by Akira Mujawar on 17/06/26.
//

#ifndef MEOWENGINE_APPLICATIONCONFIGSERIALIZER_HPP
#define MEOWENGINE_APPLICATIONCONFIGSERIALIZER_HPP


class ApplicationConfigSerializer {};


#endif //MEOWENGINE_APPLICATIONCONFIGSERIALIZER_HPP